USE "api" ;
-- ESTRUCTURA DE LA TABLA DE CANCIONES
DROP TABLE IF EXISTS canciones;
CREATE TABLE canciones (
    id INT(11) NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    artista VARCHAR(100) NOT NULL,
    fecha_lanzamiento DATE NOT NULL,
    genero VARCHAR(50),
    PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- DATOS PARA LA TABLA DE CANCIONES
LOCK TABLES canciones WRITE;
UNLOCK TABLES;
